### ISSUE TITLE
You need an API key to run this App.

### ISSUE THREAD

**Issue by CyrilFrt** [Aimanski12/ReactJS_Projects#1]
Hello i have a problem when i use this app. I dont know why but when i scan an item i have this error : "You need an API key to run this App."
But i've change the file /assets/config.js 

https://gyazo.com/ec84b80c7aea1b5bcf822952eb1c29f1?fbclid=IwAR0gKys91W20LWF2d7avENBqc0BWgD6lDUrg00wwbleRXFQcMP8phh4vQuI

https://gyazo.com/3ddea75e492ffb7a7b3541734773b431?fbclid=IwAR2Z3WXhBDbz7UOUWYC2AdIdt7chsWUQfFE2S-kHbgm15w3Fta-O0B6y3ZQ

**Comment by Aimanski12** [comment]
Hi,
I might be in a late response but just want to get through this. 
1. Make sure you have copied the right API Key.
2. The API Key is valid for 50 query calls. If you exceed, your API key will expire. You can sign up again to generate a new key.
