### ISSUE TITLE
Barcode Scanner

### ISSUE THREAD

**Issue by nkorollun** [Aimanski12/ReactJS_Projects#3]
Hello!
When I scan the first time, the onDetect (res) function is called once, when I scan the second time this function is called twice already, the third time that onDetect (res) is called three times, and so on.
How can this be fixed?

P.S. https://github.com/Aimanski12/ReactJS_Projects/blob/proj06/src/components/Scanner/Scanner.js
Line 42

**Comment by Aimanski12** [comment]
Hi. 
I might be on a late response now but i just want to get through with this.
The quagga JS renders a photo from the users camera and analyse if the photo contains any barcode.. if your camera is set up in 60fps (frames per second) that means, you are telling quagga js to scan 60 photos if they have barcodes, so be careful when you do the scanning. It should acutally work. sometimes i even get 10 scans in one rendering.
