### ISSUE TITLE
How do i clone the react scanner repo

### ISSUE THREAD

**Issue by Runo-saduwa** [Aimanski12/ReactJS_Projects#5]
im having difficulty in cloning this repo please what command should i enter exactly

**Comment by Aimanski12** [comment]
type this in your terminal;
   $ git clone https://github.com/Aimanski12/ReactJS_Projects/tree/proj06 proj-name

then type;
  cd /proj-name

then;
  $ git branch proj06

then install npm modules;
  $ npm install

then;
  $ npm start
