### ISSUE TITLE
Proj 5

### ISSUE THREAD

**Issue by Baertie** [Aimanski12/ReactJS_Projects#6]
How did you get this link : https://us-central1-camera-proj.cloudfunctions.net/storeImage?

thanks!

**Comment by Baertie** [comment]
please it is very urgent!

**Comment by Aimanski12** [comment]
The link is found on the Firebase documentation in here;
[https://firebase.google.com/docs/functions/get-started?authuser=0#deploy-and-execute-addmessage](Firebase Storage)

**Comment by Aimanski12** [comment]
The link is found on the Firebase documentation in here;
[https://firebase.google.com/docs/functions/get-started?authuser=0#deploy-and-execute-addmessage](url)
