### ISSUE TITLE
proj09

### ISSUE THREAD

**Issue by Elavarasan30** [Aimanski12/ReactJS_Projects#7]
hey hi, Aimanski actually i'am getting a error on that movie searcher app,
in App,js I'm getting a compilation error and props type erroe
![Screenshot (31)](https://user-images.githubusercontent.com/53031252/78820097-e047bb80-79f4-11ea-9b34-5ebdebd8a3ef.png)
![Screenshot (32)](https://user-images.githubusercontent.com/53031252/78820102-e2aa1580-79f4-11ea-97a5-072c20dfd4b0.png)

**Comment by Aimanski12** [comment]
Hi @Elavarasan30 

Thank you for using the project. 

The error must have come from the movie state. Make sure you check if state is not empty before you load it into you application. otherwise, they the function maps the movie state, it will give you error since the initial state is empty.

Thanks
