### ISSUE TITLE
Greetings. I really liked your video on YouTube. (proj06) Barcode Scanner.

### ISSUE THREAD

**Issue by Flidi** [Aimanski12/ReactJS_Projects#9]
Greetings. I really liked your video on YouTube. But I got a problem. I can’t figure out if I’m doing everything right.
![1](https://user-images.githubusercontent.com/60918348/79987199-c78bdb00-84b5-11ea-8095-524e318a2985.jpg)
I got the key.
![2](https://user-images.githubusercontent.com/60918348/79987349-f6a24c80-84b5-11ea-9aa9-f1f85d08d2c5.jpg)
But even after I insert it
![3](https://user-images.githubusercontent.com/60918348/79987644-5b5da700-84b6-11ea-951c-127734c1d58c.jpg)
Anyway, it tells me that I need a key. Am I doing something wrong?
Maybe I have a bad camera because without a key I was told "invalid barcode"?

Is it possible to add a read code before the message You need an API key to run this App and invalid barcode. To know that the barcode in general was read.

**Comment by Aimanski12** [comment]
Hi @Flidi ,

Thank you for appreciating my work. The app is run by Bardcode API. A public library for barcodes. The thing is, i needs an API key. If you signup to their website, they will provide you with a free api key but for only 50 queries. You can put the API key at ./assets/config.js file.

Thanks
